### ISSUE TITLE
Add support for markdown keyboard shortcuts

### ISSUE THREAD

**Issue by gregh** [usememos/gomark#2]
### Describe the solution you'd like

It would be great if we could do:
`<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Space</kbd>`

That becomes:

<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Space</kbd>

Found it here:
[https://gist.github.com/bittner/f3e2804e06c663510e939ca569ee483e#file-keyboard-keys-md](url)

### Type of feature

User Experience (UX)

### Additional context

I have a lot of notes that have keyboard shortcuts and just thought they could be prettier.

**Comment by RoccoSmit** [comment]
@gregh would the inline code markup (https://www.usememos.com/docs/getting-started/content-syntax#code) work for this?

\`Ctrl\` + \`Alt\` + \`Space\` would look like 
![image](https://github.com/user-attachments/assets/3f60b685-a8e1-4718-8b72-1d02fe57b673)

Or are you after a more descriptive tag as well?

**Comment by gregh** [comment]
That works for me! Thanks.
